### ISSUE TITLE
"<" character in field value causes subsequent field text to be omitted from PDF 

### ISSUE THREAD

**Issue by lsgs** [BCCHR-IT/custom-template-engine#57] opened 2023-11-16 06:53 UTC
Where a "<" character is present in field text, e.g. "<100mg", and there is no whitespace between "<" and the subsequent character, any subsequent text in the field is omitted from the text written to the PDF. 

Example: PDF should read "narrative <historical accuracy" but instead includes just "narrative "
![image](https://github.com/BCCHR-IT/custom-template-engine/assets/7444426/29f0ad78-0775-402e-99cb-1b6b73629e9b)

**Comment by Seaborg** [comment] 2023-11-16 11:36
Yes, I can confirm this one. I doesn't like it, perhaps it's treated as operator.

**Comment by BCCHR-IT** [comment] 2023-11-16 17:06
Hi @lsgs and @Seaborg ,

Can you tell me what version of the CTE you are using? I ask because while I can replicate this issue on our production version of CTE (v4.0.0), I can't replicate this issue on the current development branch for it (which will be v4.1). I'm trying to trace out the cause, and I'm trying to see if it's the CTE code itself, or changes in one of the libraries like dompdf, smarty, or ckeditor.

Here is my test string:
`A bare < shows up, so does a bare > but no whitespace makes it look like <test <5mg <testing> &lt;test&gt;`

That gives me this in what will be CTE v4.1:
![image](https://github.com/BCCHR-IT/custom-template-engine/assets/49417667/37ffb2b9-6d82-420f-8f51-1464be06e79d)

And this in the generated PDF:
![image](https://github.com/BCCHR-IT/custom-template-engine/assets/49417667/b509a3d4-5192-4645-867c-4dbac6ba8286)

It looks like the current dev branch is automatically inserting a space character after < symbols followed by a letter. It will also translate the less-than HTML entity &lt; into a < and add a space.

**Comment by lsgs** [comment] 2023-11-16 20:40
I'm using my fork with the additional features. It is based on 4.0.0 though, so it's good news if your newer version is showing better handling of these scenarios.

**Comment by lsgs** [comment] 2023-11-16 20:41
Sorry - didn't mean to save and close, just comment!

**Comment by Seaborg** [comment] 2023-11-17 09:27
v4.0.0

**Comment by BCCHR-IT** [comment] 2024-05-30 20:19
Hi @lsgs , we've release the v4.1 branch, which includes better handling of greater than and less than signs in the templates from upgrading the libraries used, so I will close this issue.

**Closed as completed by BCCHR-IT** 2024-05-30 20:19 UTC
